resolutions = [512]

enable_ar_bucket = true
min_ar = 0.5
max_ar = 2.0
num_ar_buckets = 9

num_repeats = 1  # 随心所欲

[[directory]]
# 目标图像放在这里。这些是模型要学习生成的图像。
path = '/home/anon/data/images/kontext/target'
# 控制/上下文图像放在这里，名称与相应的目标图像相同。
# 每个目标图像都必须有相应的控制图像，否则就会失败。
control_path = '/home/anon/data/images/kontext/control'

# 您可以同时在普通的 t2i 数据集上进行训练。但它们必须在不同的目录下。

# [[directory]]
# path = '/home/anon/data/images/normal_t2i_dataset'